language: c

os: linux

jobs:
  include:
    - arch: amd64
      compiler: gcc
      dist: bionic
    - arch: ppc64le
      compiler: gcc
      dist: bionic
    - arch: arm64
      compiler: gcc
      dist: bionic
    - arch: amd64
      compiler: clang
      dist: bionic
    - arch: amd64
      compiler: gcc
      dist: focal
    - arch: amd64
      compiler: gcc
      dist: xenial
    - arch: amd64
      compiler: gcc
      dist: trusty
    - arch: amd64
      compiler: gcc
      dist: precise

env:
  global:
    - MAKEFLAGS="-j 2"

install:
  - autoreconf --install

script:
  - ./configure && make
  - src/detox -V
  - tests/test.sh src/detox
