language: c

os: linux

dist: bionic

jobs:
  include:
    - arch: amd64
      compiler: gcc
    - arch: ppc64le
      compiler: gcc
    - arch: arm64
      compiler: gcc
    - arch: amd64
      compiler: clang

env:
  global:
    - MAKEFLAGS="-j 2"

install:
  - autoreconf --install

script:
  - ./configure && make
  - src/detox -V
  - tests/test.sh src/detox
