language: c
arch:
  - amd64
  - ppc64le

compiler:
  - gcc
  - clang

os: linux

dist:
  - xenial
  - bionic

env:
  global:
    - MAKEFLAGS="-j 2"

install:
  - autoreconf --install

script:
  - ./configure && make
  - tests/test.sh src/detox
