name: Test build and deploy process on main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: simple test
      run: bin/simple-test.sh
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: simple test
      run: bin/simple-test.sh
