name: Test build and deploy process on version 1 branch

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: legacy unit tests
      run: ./tests/test.sh src/detox
    - name: make distcheck
      run: make distcheck

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: brew install
      run: brew install automake coreutils bash
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
